---
-

  hosts: node
  user: ansible
  become: true  
  gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars:
    sample: "this line copy using playbook with vars condation with haldlers"

  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Configure a MOTD (message of the day)
      ansible.builtin.copy:
        content: "{{ sample }}"
        dest: /etc/m23
      notify: MOTD changed    

  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed

